/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.login;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author luiss
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPrincipal = new javax.swing.JLabel();
        logInText = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        textoSecundario1 = new javax.swing.JLabel();
        logInText1 = new javax.swing.JLabel();
        logInText2 = new javax.swing.JLabel();
        contrasenia = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        iniciarSesion = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPrincipal.setFont(new java.awt.Font("Bitstream Vera Serif", 3, 48)); // NOI18N
        tituloPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        tituloPrincipal.setText("ELECTRONIC-HOMES");
        getContentPane().add(tituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 620, 50));

        logInText.setFont(new java.awt.Font("Bitstream Vera Serif", 3, 24)); // NOI18N
        logInText.setForeground(new java.awt.Color(0, 0, 0));
        logInText.setText("Contraseña:");
        getContentPane().add(logInText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 190, 60));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com (1) (2).png"))); // NOI18N
        getContentPane().add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 230, 230));

        textoSecundario1.setFont(new java.awt.Font("Bitstream Vera Serif", 3, 36)); // NOI18N
        textoSecundario1.setForeground(new java.awt.Color(0, 0, 0));
        textoSecundario1.setText("Tu mejor solución en electrónica");
        getContentPane().add(textoSecundario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 680, 50));

        logInText1.setFont(new java.awt.Font("Bitstream Vera Serif", 3, 36)); // NOI18N
        logInText1.setForeground(new java.awt.Color(0, 0, 0));
        logInText1.setText("Inicia Sesión para ingresar al sistema:");
        getContentPane().add(logInText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 810, 50));

        logInText2.setFont(new java.awt.Font("Bitstream Vera Serif", 3, 24)); // NOI18N
        logInText2.setForeground(new java.awt.Color(0, 0, 0));
        logInText2.setText("Nombre:");
        getContentPane().add(logInText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 130, 60));

        contrasenia.setBackground(new java.awt.Color(0, 102, 204));
        contrasenia.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        contrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contraseniaKeyPressed(evt);
            }
        });
        getContentPane().add(contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 390, 40));

        nombre.setBackground(new java.awt.Color(0, 102, 204));
        nombre.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreKeyPressed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 390, 40));

        iniciarSesion.setBackground(new java.awt.Color(0, 102, 204));
        iniciarSesion.setFont(new java.awt.Font("Anonymice Powerline", 3, 24)); // NOI18N
        iniciarSesion.setText("INICIAR SESIÓN");
        iniciarSesion.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                iniciarSesionAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionActionPerformed(evt);
            }
        });
        iniciarSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                iniciarSesionKeyPressed(evt);
            }
        });
        getContentPane().add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 230, 120));

        salir.setBackground(new java.awt.Color(0, 102, 204));
        salir.setFont(new java.awt.Font("Anonymice Powerline", 3, 24)); // NOI18N
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        salir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salirKeyPressed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, 230, 120));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoCliente.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        int response = JOptionPane.showConfirmDialog(this,"¿Quieres salir del Programa?", "SALIR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (response==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Saliendo...");
            //Salimos del programa
            System.exit(0);
        }
    }//GEN-LAST:event_salirActionPerformed

    private void nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyPressed
        if( evt.getKeyCode()==KeyEvent.VK_ENTER ) {
            contrasenia.requestFocus();
        }
    }//GEN-LAST:event_nombreKeyPressed

    private void contraseniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseniaKeyPressed
        if( evt.getKeyCode()==KeyEvent.VK_ENTER ) {
            iniciarSesion.requestFocus();
        }
    }//GEN-LAST:event_contraseniaKeyPressed

    private void iniciarSesionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iniciarSesionKeyPressed
        if( evt.getKeyCode()==KeyEvent.VK_RIGHT ) {
            salir.requestFocus();
        }
    }//GEN-LAST:event_iniciarSesionKeyPressed

    private void iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionActionPerformed
        
    }//GEN-LAST:event_iniciarSesionActionPerformed

    private void iniciarSesionAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_iniciarSesionAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarSesionAncestorAdded

    private void salirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salirKeyPressed
        if( evt.getKeyCode()==KeyEvent.VK_LEFT ) {
            iniciarSesion.requestFocus();
        }
    }//GEN-LAST:event_salirKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contrasenia;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel icono;
    private javax.swing.JButton iniciarSesion;
    private javax.swing.JLabel logInText;
    private javax.swing.JLabel logInText1;
    private javax.swing.JLabel logInText2;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton salir;
    private javax.swing.JLabel textoSecundario1;
    private javax.swing.JLabel tituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
