/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.admin;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import manejadores.ManejadorAgregarEmpleado;
import users.Empleado;

/**
 * Esta clase me permite poder agregar un nuevo empleado a través de una interfaz gráfica
 * @author luis
 */
public class AgregarEmpleado extends javax.swing.JFrame {
    
    private ManejadorAgregarEmpleado manejador = new ManejadorAgregarEmpleado();
    private Empleado empleado;
    private AdminHomePage admin;
    /**
     * Creates new form Cliente
     * @param empleado
     * @param admin
     */
    public AgregarEmpleado( Empleado empleado, AdminHomePage admin ) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.empleado = empleado;
        this.admin = admin;
        nombreEmpleado.setText(empleado.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPrincipal = new javax.swing.JLabel();
        subtitulo1 = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        nitLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        contrasenia = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        direccionLabel = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        regresarLabel = new javax.swing.JLabel();
        regresar = new javax.swing.JLabel();
        rol = new javax.swing.JComboBox<>();
        nombreEmpleado = new javax.swing.JLabel();
        nombreTitulo = new javax.swing.JLabel();
        iconoNombre = new javax.swing.JLabel();
        direccionLabel1 = new javax.swing.JLabel();
        sucursal = new javax.swing.JComboBox<>();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPrincipal.setFont(new java.awt.Font("Courier 10 Pitch", 1, 48)); // NOI18N
        tituloPrincipal.setForeground(new java.awt.Color(0, 0, 153));
        tituloPrincipal.setText("PANTALLA DE EMPLEADOS");
        getContentPane().add(tituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 610, 70));

        subtitulo1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 36)); // NOI18N
        subtitulo1.setForeground(new java.awt.Color(0, 0, 153));
        subtitulo1.setText("Agrega un Empleado");
        getContentPane().add(subtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com (10) (1).png"))); // NOI18N
        getContentPane().add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        nitLabel.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        nitLabel.setForeground(new java.awt.Color(0, 0, 153));
        nitLabel.setText("Nombre de Usuario:");
        getContentPane().add(nitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        nombreLabel.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(0, 0, 153));
        nombreLabel.setText("Contraseña:");
        getContentPane().add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        contrasenia.setBackground(new java.awt.Color(102, 255, 255));
        contrasenia.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        contrasenia.setForeground(new java.awt.Color(0, 0, 153));
        contrasenia.setEnabled(false);
        contrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contraseniaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contraseniaKeyPressed(evt);
            }
        });
        getContentPane().add(contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 230, 30));

        nombre.setBackground(new java.awt.Color(102, 255, 255));
        nombre.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 153));
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreKeyPressed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 230, 30));

        direccionLabel.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        direccionLabel.setForeground(new java.awt.Color(0, 0, 153));
        direccionLabel.setText("Rol:");
        getContentPane().add(direccionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, 20));

        agregar.setBackground(new java.awt.Color(102, 255, 255));
        agregar.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        agregar.setForeground(new java.awt.Color(0, 0, 153));
        agregar.setText("Agregar");
        agregar.setEnabled(false);
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        agregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agregarKeyPressed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 130, 50));

        regresarLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        regresarLabel.setForeground(new java.awt.Color(0, 0, 0));
        regresarLabel.setText("REGRESAR");
        getContentPane().add(regresarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, -1, -1));

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regresar.png"))); // NOI18N
        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, -1, -1));

        rol.setBackground(new java.awt.Color(102, 255, 255));
        rol.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        rol.setForeground(new java.awt.Color(0, 0, 153));
        rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Inventario", "Bodega", "Administrador" }));
        rol.setEnabled(false);
        rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolActionPerformed(evt);
            }
        });
        rol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rolKeyPressed(evt);
            }
        });
        getContentPane().add(rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 230, 30));

        nombreEmpleado.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        nombreEmpleado.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(nombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 480, 20));

        nombreTitulo.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        nombreTitulo.setForeground(new java.awt.Color(0, 0, 153));
        nombreTitulo.setText("Nombre Empleado:");
        getContentPane().add(nombreTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        iconoNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com (1).png"))); // NOI18N
        getContentPane().add(iconoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        direccionLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        direccionLabel1.setForeground(new java.awt.Color(0, 0, 153));
        direccionLabel1.setText("Sucursal:");
        getContentPane().add(direccionLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, 20));

        sucursal.setBackground(new java.awt.Color(102, 255, 255));
        sucursal.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        sucursal.setForeground(new java.awt.Color(0, 0, 153));
        sucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sucursal Central", "Sucursal Norte", "Sucursal Sur" }));
        sucursal.setEnabled(false);
        sucursal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sucursalKeyPressed(evt);
            }
        });
        getContentPane().add(sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 230, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homescreen.png"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contraseniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseniaKeyTyped
      
    }//GEN-LAST:event_contraseniaKeyTyped

    private void contraseniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseniaKeyPressed
        if( evt.getKeyCode()==KeyEvent.VK_ENTER ) {
            rol.requestFocus();
        }
    }//GEN-LAST:event_contraseniaKeyPressed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped

    }//GEN-LAST:event_nombreKeyTyped

    private void nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyPressed

        if( evt.getKeyCode()==KeyEvent.VK_ENTER ) {
            contrasenia.requestFocus();
            manejador.verificarEmpleado(nombre, contrasenia, rol, sucursal, agregar);
        }
    }//GEN-LAST:event_nombreKeyPressed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        if( contrasenia.getText().isEmpty() || nombre.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Aún hay campos vacios", "PELIGRO", JOptionPane.WARNING_MESSAGE);
            nombre.requestFocus();
        } else {
            manejador.agregarEmpleado(nombre, contrasenia, rol, sucursal, agregar);
            manejador.reiniciarVentana(nombre, contrasenia, rol, sucursal, agregar);
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void agregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agregarKeyPressed
  
    }//GEN-LAST:event_agregarKeyPressed

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
        //Regresamos al menú de manejadores
        int response = JOptionPane.showConfirmDialog(this,"¿Quieres Regresar?", "REGRESAR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (response==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Regresando...");
            //Cerramos esta ventana y procedemos a mostrar el menu manejadores
            this.setVisible(false);
            admin.setVisible(true);
            admin.setEnabled(true);
        }
    }//GEN-LAST:event_regresarMouseClicked

    private void rolKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rolKeyPressed
        if( evt.getKeyCode()==KeyEvent.VK_ENTER ) {
            if(sucursal.isEnabled()){
                sucursal.requestFocus();
            } else{
                agregar.requestFocus();
            }
            
        }
    }//GEN-LAST:event_rolKeyPressed

    private void sucursalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sucursalKeyPressed
        if( evt.getKeyCode()==KeyEvent.VK_ENTER ) {
            agregar.requestFocus();
        }
    }//GEN-LAST:event_sucursalKeyPressed

    private void rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolActionPerformed
        if( rol.getSelectedItem().toString().equals("Bodega") || rol.getSelectedItem().toString().equals("Administrador")){
            sucursal.setEnabled(false);
        } else {
            sucursal.setEnabled(true);
        }
    }//GEN-LAST:event_rolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField contrasenia;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JLabel direccionLabel1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel iconoNombre;
    private javax.swing.JLabel nitLabel;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombreEmpleado;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel nombreTitulo;
    private javax.swing.JLabel regresar;
    private javax.swing.JLabel regresarLabel;
    private javax.swing.JComboBox<String> rol;
    private javax.swing.JLabel subtitulo1;
    private javax.swing.JComboBox<String> sucursal;
    private javax.swing.JLabel tituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
