/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.venta;

import ui.bodega.*;
import electrodomesticos.Electrodomestico;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import manejadores.ManejadorHomePageBodega;
import manejadores.ManejadorVenta;
import ui.login.Login;
import users.Empleado;

/**
 *
 * @author luis
 */
public class Venta extends javax.swing.JFrame {
    
    private Empleado empleado;
    private users.Cliente cliente;
    private ManejadorVenta manejador = new ManejadorVenta();
    
    /**
     * Creates new form HomePage
     */
    public Venta( Empleado empleado ) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.empleado = empleado;
        nombreEmpleado.setText( empleado.getUsername() );
        switch ( empleado.getId_sucursal() ) {
            case 1:
                sucursalEmpleado.setText("Central");
                break;
            case 2:
                sucursalEmpleado.setText("Norte");
                break;
            case 3:
                sucursalEmpleado.setText("Sur");
                break;
            default:
                sucursalEmpleado.setText("ERROR");
        }
        manejador.llenarNombreProductos(empleado.getId_sucursal(), nombreProducto);
        buscarProducto.setEnabled(false);
        manejador.llenarTabla(this);
    }
    
    public JTable getTable(){
        return this.tabla;
    }

    public JTextField getNit() {
        return nit;
    }

    public JComboBox<String> getNombreProducto() {
        return nombreProducto;
    }

    public JButton getBuscarCliente() {
        return buscarCliente;
    }

    public JButton getEditar() {
        return editar;
    }

    public JTextField getNombre() {
        return nombre;
    }

    public void setNombre(JTextField nombre) {
        this.nombre = nombre;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconoNombre = new javax.swing.JLabel();
        iconoSucursal = new javax.swing.JLabel();
        tituloPrincipal = new javax.swing.JLabel();
        subtitulo = new javax.swing.JLabel();
        sucursalEmpleado = new javax.swing.JLabel();
        nombreEmpleado = new javax.swing.JLabel();
        nombreTitulo = new javax.swing.JLabel();
        sucursalTitulo = new javax.swing.JLabel();
        Regresar = new javax.swing.JLabel();
        logOut = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        subtitulo1 = new javax.swing.JLabel();
        nitLabel = new javax.swing.JLabel();
        nombreClienteLabel = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        cancelarVenta = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        icono = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JComboBox<>();
        tipoClienteLabel = new javax.swing.JLabel();
        nit = new javax.swing.JTextField();
        subtitulo2 = new javax.swing.JLabel();
        nombreProductoLabel = new javax.swing.JLabel();
        buscarProducto = new javax.swing.JButton();
        tipoCliente = new javax.swing.JComboBox<>();
        precioLabel = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        cantidadLabel = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        stockLabel = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        seleccionar = new javax.swing.JButton();
        existenciaLabel4 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        existenciaLabel5 = new javax.swing.JLabel();
        total1 = new javax.swing.JTextField();
        existenciaLabel6 = new javax.swing.JLabel();
        total2 = new javax.swing.JTextField();
        buscarCliente = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com (1).png"))); // NOI18N
        getContentPane().add(iconoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        iconoSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com (2) (2).png"))); // NOI18N
        getContentPane().add(iconoSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        tituloPrincipal.setFont(new java.awt.Font("Courier 10 Pitch", 1, 48)); // NOI18N
        tituloPrincipal.setForeground(new java.awt.Color(0, 0, 153));
        tituloPrincipal.setText("PANTALLA DE VENTA");
        getContentPane().add(tituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 550, 70));

        subtitulo.setFont(new java.awt.Font("Courier 10 Pitch", 0, 24)); // NOI18N
        subtitulo.setForeground(new java.awt.Color(0, 0, 153));
        subtitulo.setText("Datos del Producto");
        getContentPane().add(subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 300, -1));

        sucursalEmpleado.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        sucursalEmpleado.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(sucursalEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 460, -1));

        nombreEmpleado.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        nombreEmpleado.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(nombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 620, 20));

        nombreTitulo.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        nombreTitulo.setForeground(new java.awt.Color(0, 0, 153));
        nombreTitulo.setText("Nombre Empleado:");
        getContentPane().add(nombreTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        sucursalTitulo.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        sucursalTitulo.setForeground(new java.awt.Color(0, 0, 153));
        sucursalTitulo.setText("Sucursal:");
        getContentPane().add(sucursalTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com (4) (1).png"))); // NOI18N
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 590, -1, -1));

        logOut.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        logOut.setForeground(new java.awt.Color(1, 1, 1));
        logOut.setText("LogOut");
        getContentPane().add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 670, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 153));

        tabla.setBackground(new java.awt.Color(102, 255, 255));
        tabla.setForeground(new java.awt.Color(0, 0, 153));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, 1050, 360));

        subtitulo1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 36)); // NOI18N
        subtitulo1.setForeground(new java.awt.Color(0, 0, 153));
        subtitulo1.setText("Genera una nueva venta para la empresa.");
        getContentPane().add(subtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        nitLabel.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        nitLabel.setForeground(new java.awt.Color(0, 0, 153));
        nitLabel.setText("NIT:");
        getContentPane().add(nitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        nombreClienteLabel.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        nombreClienteLabel.setForeground(new java.awt.Color(0, 0, 153));
        nombreClienteLabel.setText("Nombre del Cliente:");
        getContentPane().add(nombreClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        nombre.setBackground(new java.awt.Color(102, 255, 255));
        nombre.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 153));
        nombre.setEnabled(false);
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreKeyPressed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 160, 30));

        cancelarVenta.setBackground(new java.awt.Color(102, 255, 255));
        cancelarVenta.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        cancelarVenta.setForeground(new java.awt.Color(0, 0, 153));
        cancelarVenta.setText("Cancelar Venta");
        cancelarVenta.setEnabled(false);
        cancelarVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cancelarVentaKeyPressed(evt);
            }
        });
        getContentPane().add(cancelarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 590, 160, 50));

        editar.setBackground(new java.awt.Color(102, 255, 255));
        editar.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        editar.setForeground(new java.awt.Color(0, 0, 153));
        editar.setText("Editar");
        editar.setEnabled(false);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        editar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editarKeyPressed(evt);
            }
        });
        getContentPane().add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 120, 40));

        modificar.setBackground(new java.awt.Color(102, 255, 255));
        modificar.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        modificar.setForeground(new java.awt.Color(0, 0, 153));
        modificar.setText("Generar Venta");
        modificar.setEnabled(false);
        modificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modificarKeyPressed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 590, 190, 50));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com (8) (1).png"))); // NOI18N
        getContentPane().add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, -1, -1));

        nombreProducto.setBackground(new java.awt.Color(102, 255, 255));
        nombreProducto.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        nombreProducto.setForeground(new java.awt.Color(0, 0, 153));
        nombreProducto.setEnabled(false);
        nombreProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nombreProductoItemStateChanged(evt);
            }
        });
        nombreProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreProductoMouseClicked(evt);
            }
        });
        nombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProductoActionPerformed(evt);
            }
        });
        getContentPane().add(nombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 220, 30));

        tipoClienteLabel.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        tipoClienteLabel.setForeground(new java.awt.Color(0, 0, 153));
        tipoClienteLabel.setText("Tipo Cliente:");
        getContentPane().add(tipoClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        nit.setBackground(new java.awt.Color(102, 255, 255));
        nit.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        nit.setForeground(new java.awt.Color(0, 0, 153));
        nit.setEnabled(false);
        nit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nitKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nitKeyPressed(evt);
            }
        });
        getContentPane().add(nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 160, 30));

        subtitulo2.setFont(new java.awt.Font("Courier 10 Pitch", 0, 24)); // NOI18N
        subtitulo2.setForeground(new java.awt.Color(0, 0, 153));
        subtitulo2.setText("Datos del Cliente");
        getContentPane().add(subtitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 240, -1));

        nombreProductoLabel.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        nombreProductoLabel.setForeground(new java.awt.Color(0, 0, 153));
        nombreProductoLabel.setText("Nombre Producto:");
        getContentPane().add(nombreProductoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        buscarProducto.setBackground(new java.awt.Color(102, 255, 255));
        buscarProducto.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        buscarProducto.setForeground(new java.awt.Color(0, 0, 153));
        buscarProducto.setText("Buscar");
        buscarProducto.setEnabled(false);
        buscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProductoActionPerformed(evt);
            }
        });
        buscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarProductoKeyPressed(evt);
            }
        });
        getContentPane().add(buscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 120, 40));

        tipoCliente.setBackground(new java.awt.Color(102, 255, 255));
        tipoCliente.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        tipoCliente.setForeground(new java.awt.Color(0, 0, 153));
        tipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C/F", "Cliente" }));
        tipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(tipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 210, 30));

        precioLabel.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        precioLabel.setForeground(new java.awt.Color(0, 0, 153));
        precioLabel.setText("Precio:");
        getContentPane().add(precioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, -1, -1));

        precio.setBackground(new java.awt.Color(102, 255, 255));
        precio.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        precio.setForeground(new java.awt.Color(0, 0, 153));
        precio.setEnabled(false);
        precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                precioKeyPressed(evt);
            }
        });
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 110, 30));

        cantidadLabel.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        cantidadLabel.setForeground(new java.awt.Color(0, 0, 153));
        cantidadLabel.setText("Cantidad:");
        getContentPane().add(cantidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, -1, -1));

        cantidad.setBackground(new java.awt.Color(102, 255, 255));
        cantidad.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 0, 153));
        cantidad.setEnabled(false);
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadKeyPressed(evt);
            }
        });
        getContentPane().add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 120, 30));

        stockLabel.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        stockLabel.setForeground(new java.awt.Color(0, 0, 153));
        stockLabel.setText("Stock:");
        getContentPane().add(stockLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 70, -1));

        stock.setBackground(new java.awt.Color(102, 255, 255));
        stock.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        stock.setForeground(new java.awt.Color(0, 0, 153));
        stock.setEnabled(false);
        stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stockKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stockKeyPressed(evt);
            }
        });
        getContentPane().add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 130, 30));

        agregar.setBackground(new java.awt.Color(102, 255, 255));
        agregar.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        agregar.setForeground(new java.awt.Color(0, 0, 153));
        agregar.setText("Agregar");
        agregar.setEnabled(false);
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        agregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agregarKeyPressed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 130, 50));

        eliminar.setBackground(new java.awt.Color(102, 255, 255));
        eliminar.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        eliminar.setForeground(new java.awt.Color(0, 0, 153));
        eliminar.setText("Eliminar");
        eliminar.setEnabled(false);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        eliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eliminarKeyPressed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, 130, 50));

        seleccionar.setBackground(new java.awt.Color(102, 255, 255));
        seleccionar.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        seleccionar.setForeground(new java.awt.Color(0, 0, 153));
        seleccionar.setText("Seleccionar");
        seleccionar.setEnabled(false);
        seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarActionPerformed(evt);
            }
        });
        seleccionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                seleccionarKeyPressed(evt);
            }
        });
        getContentPane().add(seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 120, 40));

        existenciaLabel4.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        existenciaLabel4.setForeground(new java.awt.Color(0, 0, 153));
        existenciaLabel4.setText("Total:");
        getContentPane().add(existenciaLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 640, -1, -1));

        total.setBackground(new java.awt.Color(102, 255, 255));
        total.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        total.setForeground(new java.awt.Color(0, 0, 153));
        total.setEnabled(false);
        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalKeyPressed(evt);
            }
        });
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 640, 210, 30));

        existenciaLabel5.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        existenciaLabel5.setForeground(new java.awt.Color(0, 0, 153));
        existenciaLabel5.setText("Descuento:");
        getContentPane().add(existenciaLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 640, -1, -1));

        total1.setBackground(new java.awt.Color(102, 255, 255));
        total1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        total1.setForeground(new java.awt.Color(0, 0, 153));
        total1.setEnabled(false);
        total1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                total1KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                total1KeyPressed(evt);
            }
        });
        getContentPane().add(total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 640, 210, 30));

        existenciaLabel6.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        existenciaLabel6.setForeground(new java.awt.Color(0, 0, 153));
        existenciaLabel6.setText("Total sin Descuento:");
        getContentPane().add(existenciaLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 590, -1, -1));

        total2.setBackground(new java.awt.Color(102, 255, 255));
        total2.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        total2.setForeground(new java.awt.Color(0, 0, 153));
        total2.setEnabled(false);
        total2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                total2KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                total2KeyPressed(evt);
            }
        });
        getContentPane().add(total2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 590, 210, 30));

        buscarCliente.setBackground(new java.awt.Color(102, 255, 255));
        buscarCliente.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        buscarCliente.setForeground(new java.awt.Color(0, 0, 153));
        buscarCliente.setText("Buscar");
        buscarCliente.setEnabled(false);
        buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteActionPerformed(evt);
            }
        });
        buscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarClienteKeyPressed(evt);
            }
        });
        getContentPane().add(buscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 120, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homescreen.png"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        //Regresamos al menú de manejadores
        int response = JOptionPane.showConfirmDialog(this,"¿Quieres Cerrar Sesión", "CERRAR SESIÓN",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (response==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Cerrando Sesión...");
            //Cerramos esta ventana y procedemos a mostrar el menu manejadores
            this.setVisible(false);
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_RegresarMouseClicked

    private void nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyPressed

    }//GEN-LAST:event_nombreKeyPressed

    private void editarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editarKeyPressed

    }//GEN-LAST:event_editarKeyPressed

    private void modificarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modificarKeyPressed

    }//GEN-LAST:event_modificarKeyPressed

    private void cancelarVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancelarVentaKeyPressed

    }//GEN-LAST:event_cancelarVentaKeyPressed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        
    }//GEN-LAST:event_nombreKeyTyped

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        cliente = new users.Cliente();
        cliente.setNit(nit.getText());
        manejador.editarCliente(cliente, this);
    }//GEN-LAST:event_editarActionPerformed

    private void nitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nitKeyTyped
        char validar=evt.getKeyChar();
        if ( !(Character.isDigit(validar)) && validar!= '\n' && validar!= '\b' ){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar solo números", "ERROR", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_nitKeyTyped

    private void nitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nitKeyPressed
        if( evt.getKeyCode()==KeyEvent.VK_ENTER ){
            buscarCliente.setEnabled(true);
            buscarCliente.requestFocus();
        
        }
    }//GEN-LAST:event_nitKeyPressed

    private void buscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductoActionPerformed
        manejador.agregarCampos(precio, stock, nombreProducto, cantidad);
        buscarProducto.setEnabled(false);
        cantidad.setEnabled(true);
        cantidad.requestFocus();
    }//GEN-LAST:event_buscarProductoActionPerformed

    private void buscarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarProductoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarProductoKeyPressed

    private void precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioKeyTyped
        
    }//GEN-LAST:event_precioKeyTyped

    private void precioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioKeyPressed

    private void cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyTyped
        char validar=evt.getKeyChar();
        if ( !(Character.isDigit(validar)) && validar!= '\n' && validar!= '\b' ){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar solo números", "ERROR", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_cantidadKeyTyped

    private void cantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER ){
            if( Integer.parseInt(cantidad.getText()) > Integer.parseInt( stock.getText() )){
                JOptionPane.showMessageDialog(this, "Estás solicitando más de las unidades disponibles", "PELIGRO", JOptionPane.WARNING_MESSAGE);
                cantidad.setText("");
            } else {
                cantidad.setEnabled(false);
                agregar.setEnabled(true);
                agregar.requestFocus();
            }
        }
    }//GEN-LAST:event_cantidadKeyPressed

    private void stockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_stockKeyTyped

    private void stockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockKeyPressed

    private void agregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agregarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarKeyPressed

    private void eliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eliminarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarKeyPressed

    private void seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarActionPerformed
        if( tipoCliente.getSelectedIndex() == 0 ){
            nombreProducto.setEnabled(true);
            nombreProducto.requestFocus();
        } else{
            nit.setEnabled(true);
            nit.requestFocus();
        }
        seleccionar.setEnabled(false);
        tipoCliente.setEnabled(false);
    }//GEN-LAST:event_seleccionarActionPerformed

    private void seleccionarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seleccionarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarKeyPressed

    private void totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_totalKeyTyped

    private void totalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalKeyPressed

    private void total1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_total1KeyTyped

    private void total1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_total1KeyPressed

    private void total2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_total2KeyTyped

    private void total2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_total2KeyPressed

    private void buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteActionPerformed
        manejador.buscarCliente(nit,nombre,buscarCliente,editar,this, nombreProducto);
        cantidad.requestFocus();
    }//GEN-LAST:event_buscarClienteActionPerformed

    private void buscarClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarClienteKeyPressed

    private void tipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoClienteActionPerformed
        seleccionar.setEnabled(true);
        seleccionar.requestFocus();
    }//GEN-LAST:event_tipoClienteActionPerformed

    private void nombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProductoActionPerformed
        buscarProducto.setEnabled(true);
        cantidad.setEnabled(false);
        cantidad.setText("");
    }//GEN-LAST:event_nombreProductoActionPerformed

    private void nombreProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreProductoMouseClicked
        
    }//GEN-LAST:event_nombreProductoMouseClicked

    private void nombreProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nombreProductoItemStateChanged
        
    }//GEN-LAST:event_nombreProductoItemStateChanged

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        manejador.agregarVenta(cantidad, this, total);
        manejador.reiniciarCompra(stock, precio, cantidad, agregar, nombreProducto, eliminar);
    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        manejador.eliminarCompra(tabla, this, nombreProducto, eliminar, total);
    }//GEN-LAST:event_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Regresar;
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscarCliente;
    private javax.swing.JButton buscarProducto;
    private javax.swing.JButton cancelarVenta;
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel existenciaLabel4;
    private javax.swing.JLabel existenciaLabel5;
    private javax.swing.JLabel existenciaLabel6;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel iconoNombre;
    private javax.swing.JLabel iconoSucursal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logOut;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nit;
    private javax.swing.JLabel nitLabel;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombreClienteLabel;
    private javax.swing.JLabel nombreEmpleado;
    private javax.swing.JComboBox<String> nombreProducto;
    private javax.swing.JLabel nombreProductoLabel;
    private javax.swing.JLabel nombreTitulo;
    private javax.swing.JTextField precio;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JButton seleccionar;
    private javax.swing.JTextField stock;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JLabel subtitulo1;
    private javax.swing.JLabel subtitulo2;
    private javax.swing.JLabel sucursalEmpleado;
    private javax.swing.JLabel sucursalTitulo;
    private javax.swing.JTable tabla;
    private javax.swing.JComboBox<String> tipoCliente;
    private javax.swing.JLabel tipoClienteLabel;
    private javax.swing.JLabel tituloPrincipal;
    private javax.swing.JTextField total;
    private javax.swing.JTextField total1;
    private javax.swing.JTextField total2;
    // End of variables declaration//GEN-END:variables
}
