/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.venta;

import ui.bodega.*;
import electrodomesticos.Electrodomestico;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import manejadores.ManejadorHomePageBodega;
import ui.login.Login;
import users.Empleado;

/**
 *
 * @author luis
 */
public class Venta extends javax.swing.JFrame {
    
    ManejadorHomePageBodega manejador = new ManejadorHomePageBodega();
    Empleado empleado;
    Electrodomestico electrodomestico = new Electrodomestico();
    /**
     * Creates new form HomePage
     */
    public Venta( Empleado empleado ) {
        initComponents();
        this.setLocationRelativeTo(null);
        nombreEmpleado.setText( empleado.getUsername() );
        this.empleado = empleado;
        this.tabla.setEnabled(false);
//        manejador.llenarTabla(this);
    }
    
    public JTable getTable(){
        return this.tabla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconoNombre = new javax.swing.JLabel();
        iconoSucursal = new javax.swing.JLabel();
        tituloPrincipal = new javax.swing.JLabel();
        subtitulo = new javax.swing.JLabel();
        sucursalEmpleado = new javax.swing.JLabel();
        nombreEmpleado = new javax.swing.JLabel();
        nombreTitulo = new javax.swing.JLabel();
        sucursalTitulo = new javax.swing.JLabel();
        Regresar = new javax.swing.JLabel();
        logOut = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        subtitulo1 = new javax.swing.JLabel();
        existenciaLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        existencia = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        eliminar = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        nombreLabel1 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        subtitulo2 = new javax.swing.JLabel();
        nombreLabel2 = new javax.swing.JLabel();
        agregar1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        existenciaLabel1 = new javax.swing.JLabel();
        existencia1 = new javax.swing.JTextField();
        existenciaLabel2 = new javax.swing.JLabel();
        existencia2 = new javax.swing.JTextField();
        existenciaLabel3 = new javax.swing.JLabel();
        existencia3 = new javax.swing.JTextField();
        Agregar = new javax.swing.JButton();
        eliminar1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com (1).png"))); // NOI18N
        getContentPane().add(iconoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        iconoSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com (2) (2).png"))); // NOI18N
        getContentPane().add(iconoSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        tituloPrincipal.setFont(new java.awt.Font("Courier 10 Pitch", 1, 48)); // NOI18N
        tituloPrincipal.setForeground(new java.awt.Color(0, 0, 153));
        tituloPrincipal.setText("PANTALLA DE VENTA");
        getContentPane().add(tituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 550, 70));

        subtitulo.setFont(new java.awt.Font("Courier 10 Pitch", 0, 24)); // NOI18N
        subtitulo.setForeground(new java.awt.Color(0, 0, 153));
        subtitulo.setText("Datos del Producto");
        getContentPane().add(subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 300, -1));

        sucursalEmpleado.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        sucursalEmpleado.setForeground(new java.awt.Color(0, 0, 153));
        sucursalEmpleado.setText("Bodega");
        getContentPane().add(sucursalEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 60, -1));

        nombreEmpleado.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        nombreEmpleado.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(nombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 690, -1));

        nombreTitulo.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        nombreTitulo.setForeground(new java.awt.Color(0, 0, 153));
        nombreTitulo.setText("Nombre Empleado:");
        getContentPane().add(nombreTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        sucursalTitulo.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        sucursalTitulo.setForeground(new java.awt.Color(0, 0, 153));
        sucursalTitulo.setText("Sucursal:");
        getContentPane().add(sucursalTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com (4) (1).png"))); // NOI18N
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 590, -1, -1));

        logOut.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        logOut.setForeground(new java.awt.Color(1, 1, 1));
        logOut.setText("LogOut");
        getContentPane().add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 670, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 153));

        tabla.setBackground(new java.awt.Color(102, 255, 255));
        tabla.setForeground(new java.awt.Color(0, 0, 153));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, 850, 360));

        subtitulo1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 36)); // NOI18N
        subtitulo1.setForeground(new java.awt.Color(0, 0, 153));
        subtitulo1.setText("Genera una nueva venta para la empresa.");
        getContentPane().add(subtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        existenciaLabel.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        existenciaLabel.setForeground(new java.awt.Color(0, 0, 153));
        existenciaLabel.setText("Nombre Producto:");
        getContentPane().add(existenciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        nombreLabel.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(0, 0, 153));
        nombreLabel.setText("NIT:");
        getContentPane().add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        precioLabel.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        precioLabel.setForeground(new java.awt.Color(0, 0, 153));
        precioLabel.setText("Datos del Cliente:");
        getContentPane().add(precioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        existencia.setBackground(new java.awt.Color(102, 255, 255));
        existencia.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        existencia.setForeground(new java.awt.Color(0, 0, 153));
        existencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                existenciaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                existenciaKeyPressed(evt);
            }
        });
        getContentPane().add(existencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 220, 30));

        nombre.setBackground(new java.awt.Color(102, 255, 255));
        nombre.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 153));
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreKeyPressed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 160, 30));

        eliminar.setBackground(new java.awt.Color(102, 255, 255));
        eliminar.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        eliminar.setForeground(new java.awt.Color(0, 0, 153));
        eliminar.setText("Cancelar");
        eliminar.setEnabled(false);
        eliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eliminarKeyPressed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 600, 130, 50));

        agregar.setBackground(new java.awt.Color(102, 255, 255));
        agregar.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        agregar.setForeground(new java.awt.Color(0, 0, 153));
        agregar.setText("Buscar");
        agregar.setEnabled(false);
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        agregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agregarKeyPressed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 120, 40));

        modificar.setBackground(new java.awt.Color(102, 255, 255));
        modificar.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        modificar.setForeground(new java.awt.Color(0, 0, 153));
        modificar.setText("Generar Venta");
        modificar.setEnabled(false);
        modificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modificarKeyPressed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 600, 190, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com (8) (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(102, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 160, 30));

        nombreLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        nombreLabel1.setForeground(new java.awt.Color(0, 0, 153));
        nombreLabel1.setText("Tipo Cliente:");
        getContentPane().add(nombreLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        nombre1.setBackground(new java.awt.Color(102, 255, 255));
        nombre1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        nombre1.setForeground(new java.awt.Color(0, 0, 153));
        nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre1KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombre1KeyPressed(evt);
            }
        });
        getContentPane().add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 160, 30));

        subtitulo2.setFont(new java.awt.Font("Courier 10 Pitch", 0, 24)); // NOI18N
        subtitulo2.setForeground(new java.awt.Color(0, 0, 153));
        subtitulo2.setText("Datos del Cliente");
        getContentPane().add(subtitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 240, -1));

        nombreLabel2.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        nombreLabel2.setForeground(new java.awt.Color(0, 0, 153));
        nombreLabel2.setText("Codigo Producto:");
        getContentPane().add(nombreLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        agregar1.setBackground(new java.awt.Color(102, 255, 255));
        agregar1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        agregar1.setForeground(new java.awt.Color(0, 0, 153));
        agregar1.setText("Buscar");
        agregar1.setEnabled(false);
        agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar1ActionPerformed(evt);
            }
        });
        agregar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agregar1KeyPressed(evt);
            }
        });
        getContentPane().add(agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 120, 40));

        jComboBox2.setBackground(new java.awt.Color(102, 255, 255));
        jComboBox2.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(0, 0, 153));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 210, 30));

        existenciaLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        existenciaLabel1.setForeground(new java.awt.Color(0, 0, 153));
        existenciaLabel1.setText("Precio:");
        getContentPane().add(existenciaLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, -1));

        existencia1.setBackground(new java.awt.Color(102, 255, 255));
        existencia1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        existencia1.setForeground(new java.awt.Color(0, 0, 153));
        existencia1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                existencia1KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                existencia1KeyPressed(evt);
            }
        });
        getContentPane().add(existencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 110, 30));

        existenciaLabel2.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        existenciaLabel2.setForeground(new java.awt.Color(0, 0, 153));
        existenciaLabel2.setText("Cantidad:");
        getContentPane().add(existenciaLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));

        existencia2.setBackground(new java.awt.Color(102, 255, 255));
        existencia2.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        existencia2.setForeground(new java.awt.Color(0, 0, 153));
        existencia2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                existencia2KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                existencia2KeyPressed(evt);
            }
        });
        getContentPane().add(existencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 120, 30));

        existenciaLabel3.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        existenciaLabel3.setForeground(new java.awt.Color(0, 0, 153));
        existenciaLabel3.setText("Stock:");
        getContentPane().add(existenciaLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, -1, -1));

        existencia3.setBackground(new java.awt.Color(102, 255, 255));
        existencia3.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        existencia3.setForeground(new java.awt.Color(0, 0, 153));
        existencia3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                existencia3KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                existencia3KeyPressed(evt);
            }
        });
        getContentPane().add(existencia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 100, 30));

        Agregar.setBackground(new java.awt.Color(102, 255, 255));
        Agregar.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        Agregar.setForeground(new java.awt.Color(0, 0, 153));
        Agregar.setText("Agregar");
        Agregar.setEnabled(false);
        Agregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AgregarKeyPressed(evt);
            }
        });
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 130, 50));

        eliminar1.setBackground(new java.awt.Color(102, 255, 255));
        eliminar1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        eliminar1.setForeground(new java.awt.Color(0, 0, 153));
        eliminar1.setText("Eliminar");
        eliminar1.setEnabled(false);
        eliminar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eliminar1KeyPressed(evt);
            }
        });
        getContentPane().add(eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 130, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homescreen.png"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        //Regresamos al menú de manejadores
        int response = JOptionPane.showConfirmDialog(this,"¿Quieres Cerrar Sesión", "CERRAR SESIÓN",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (response==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Cerrando Sesión...");
            //Cerramos esta ventana y procedemos a mostrar el menu manejadores
            this.setVisible(false);
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_RegresarMouseClicked

    private void nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyPressed
//        manejador.verificarAgregar(nombre, precio, existencia, agregar);
        if( evt.getKeyCode()==KeyEvent.VK_ENTER ) {
//            precio.requestFocus();
        }
    }//GEN-LAST:event_nombreKeyPressed

    private void existenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_existenciaKeyTyped
        //Verificamos que en este Jtextfield solo hayan números
        char validar=evt.getKeyChar();
        if (Character.isLetter(validar) || validar == '.'){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar solo números", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_existenciaKeyTyped

    private void existenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_existenciaKeyPressed
//        manejador.verificarAgregar(nombre, precio, existencia, agregar);
        if( evt.getKeyCode()==KeyEvent.VK_ENTER ) {
            if( agregar.isEnabled() ){
                agregar.requestFocus();
            } else {
                nombre.requestFocus();
            }
        }
    }//GEN-LAST:event_existenciaKeyPressed

    private void agregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agregarKeyPressed
        if( evt.getKeyCode()==KeyEvent.VK_RIGHT ) {
            modificar.requestFocus();
        }
    }//GEN-LAST:event_agregarKeyPressed

    private void modificarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modificarKeyPressed
        if( evt.getKeyCode()==KeyEvent.VK_RIGHT ) {
            eliminar.requestFocus();
        } else if( evt.getKeyCode()==KeyEvent.VK_LEFT ) {
            agregar.requestFocus();
        }
    }//GEN-LAST:event_modificarKeyPressed

    private void eliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eliminarKeyPressed
        if( evt.getKeyCode()==KeyEvent.VK_LEFT ) {
            modificar.requestFocus();
        }
//        manejador.verificarAgregar(nombre, precio, existencia, agregar);
    }//GEN-LAST:event_eliminarKeyPressed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        
    }//GEN-LAST:event_nombreKeyTyped

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
//        if( manejador.verificarLLenado(this, nombre, precio, existencia) ){
//            electrodomestico.setNombre(nombre.getText());
//            electrodomestico.setPrecio(Float.parseFloat(precio.getText()));
//            electrodomestico.setExistencia(Integer.parseInt(existencia.getText()));
//            manejador.addProducto(this, electrodomestico);
//            manejador.limpiezaCampos(nombre, precio, existencia, agregar, eliminar, eliminar);
//        }
    }//GEN-LAST:event_agregarActionPerformed

    private void nombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre1KeyTyped

    private void nombre1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre1KeyPressed

    private void agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar1ActionPerformed

    private void agregar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agregar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar1KeyPressed

    private void existencia1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_existencia1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_existencia1KeyTyped

    private void existencia1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_existencia1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_existencia1KeyPressed

    private void existencia2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_existencia2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_existencia2KeyTyped

    private void existencia2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_existencia2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_existencia2KeyPressed

    private void existencia3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_existencia3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_existencia3KeyTyped

    private void existencia3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_existencia3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_existencia3KeyPressed

    private void AgregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgregarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarKeyPressed

    private void eliminar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eliminar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JLabel Regresar;
    private javax.swing.JButton agregar;
    private javax.swing.JButton agregar1;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton eliminar1;
    private javax.swing.JTextField existencia;
    private javax.swing.JTextField existencia1;
    private javax.swing.JTextField existencia2;
    private javax.swing.JTextField existencia3;
    private javax.swing.JLabel existenciaLabel;
    private javax.swing.JLabel existenciaLabel1;
    private javax.swing.JLabel existenciaLabel2;
    private javax.swing.JLabel existenciaLabel3;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iconoNombre;
    private javax.swing.JLabel iconoSucursal;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logOut;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombre1;
    private javax.swing.JLabel nombreEmpleado;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel nombreLabel1;
    private javax.swing.JLabel nombreLabel2;
    private javax.swing.JLabel nombreTitulo;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JLabel subtitulo1;
    private javax.swing.JLabel subtitulo2;
    private javax.swing.JLabel sucursalEmpleado;
    private javax.swing.JLabel sucursalTitulo;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel tituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
